sudo: required
dist: trusty
language: python
python:
 - 2.7
 - 3.4
 - 3.5
before_install:
 - sudo apt-get update
 - sudo apt-get -y install apt-transport-https ca-certificates software-properties-common
 - sudo apt-key adv --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys 58118E89F3A912897C070ADBF76221572C52609D
 - sudo add-apt-repository "deb https://apt.dockerproject.org/repo ubuntu-$(lsb_release -sc) main" 
 - sudo apt-get update
 - sudo apt-get install docker-engine
 - sudo service docker start
 - curl -L https://github.com/docker/machine/releases/download/v0.6.0/docker-machine-`uname -s`-`uname -m` -o docker-machine
 - sudo mv docker-machine /usr/local/bin/.
 - sudo chmod +x /usr/local/bin/docker-machine
install:
 - pip install .
script:
 - nosetests
